# Generated by Django 5.2.1 on 2026-04-17 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('short_description', models.CharField(max_length=220)),
                ('image', models.ImageField(blank=True, null=True, upload_to='courses/')),
                ('age_range', models.CharField(blank=True, default='من 6 أشهر حتى 9 سنوات', max_length=60)),
                ('cta_text', models.CharField(default='ابدأ الآن', max_length=60)),
                ('order', models.PositiveIntegerField(default=1)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
