# Generated by Django 5.2.1 on 2026-04-23 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='tags',
            field=models.CharField(blank=True, help_text='مثال: نشاط, لغة', max_length=120),
        ),
    ]
