# Generated by Django 5.2.1 on 2026-04-23 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='tags',
        ),
        migrations.AddField(
            model_name='course',
            name='tag',
            field=models.CharField(blank=True, default='لغة', help_text='مثال: نشاط, لغة', max_length=120),
        ),
    ]
