# Generated by Django 5.2.1 on 2026-04-17 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('icon', models.CharField(blank=True, help_text='مثال: star, school, sparkles', max_length=50)),
                ('order', models.PositiveIntegerField(default=1)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='IntroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_key', models.CharField(choices=[('about', 'من نحن'), ('mission', 'رسالتنا'), ('custom', 'قسم تعريفي إضافي')], default='custom', max_length=20)),
                ('title', models.CharField(max_length=160)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='intro_sections/')),
                ('order', models.PositiveIntegerField(default=1)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='العربية لغتي', max_length=120)),
                ('hero_title', models.CharField(default='نتعلّم ونلعب ونبني جيلاً مبدعاً', max_length=255)),
                ('hero_subtitle', models.CharField(default='منال باسم بركات - حمادي', max_length=255)),
                ('hero_description', models.TextField(default='منشدة تربوية ومعالجة تعليم ملائم وعسر تعليمي')),
                ('cta_text', models.CharField(default='ابدأ الآن', max_length=60)),
                ('phone', models.CharField(default='0522180851', max_length=30)),
                ('whatsapp', models.CharField(default='0522180851', max_length=30)),
                ('location_text', models.CharField(default='كابول - دوزيا شارع السهل', max_length=255)),
                ('instagram_url', models.URLField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
            ],
        ),
    ]
