# Generated by Django 5.2.1 on 2026-04-23 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='introsection',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='intro_sections/'),
        ),
    ]
