# Generated by Django 5.2.1 on 2026-04-23 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_introsection_image2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='icon',
            field=models.ImageField(blank=True, upload_to='feature_icons/'),
        ),
    ]
